# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

analyzer:
  errors:
    missing_return: error
    dead_code: warning

linter:
  rules:
    - avoid_print: true
    - prefer_single_quotes: true
    - avoid_unnecessary_containers: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
