// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3ULmf4EUX9Aj9TnoprBUfkSmA1qh4Oc',
    appId: '1:96954918433:android:17e92dcabbafe017626560',
    messagingSenderId: '96954918433',
    projectId: 'fitnexus-app-61488',
    storageBucket: 'fitnexus-app-61488.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gt1A9rCYTBgCvM_aMSyGMKklnkoqizE',
    appId: '1:96954918433:ios:b9fc85d75014686c626560',
    messagingSenderId: '96954918433',
    projectId: 'fitnexus-app-61488',
    storageBucket: 'fitnexus-app-61488.firebasestorage.app',
    iosClientId: '96954918433-fc0aurkh8m3agvbuvucdgf04cvv8kdhs.apps.googleusercontent.com',
    iosBundleId: 'com.fitnexus.fitnexus',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrSBgqsTWoMrqcYal-L1jN5z94ubzw6G0',
    appId: '1:96954918433:web:3b2aa447a04cc754626560',
    messagingSenderId: '96954918433',
    projectId: 'fitnexus-app-61488',
    authDomain: 'fitnexus-app-61488.firebaseapp.com',
    storageBucket: 'fitnexus-app-61488.firebasestorage.app',
  );
}
